"""Adapter for the MIT whiteboard streaming renderer used by Drawing jobs.

It keeps the reference renderer intact while applying Video Clone's selected
duration, FPS and output resolution.  In particular, short previews reserve a
small gaze segment instead of consuming the entire clip before any ink lands.
"""
from __future__ import annotations

import argparse
import datetime
import importlib.util
import math
import os
import subprocess
import sys
import time
from pathlib import Path

import cv2
import numpy as np


def _opencl_device() -> tuple[bool, str]:
    """Shared cross-platform OpenCL detection — delegates to pipeline.core.accel
    when available (full backend path), falls back to direct cv2 probe otherwise."""
    try:
        from pipeline.core.accel import opencl_device
        return opencl_device()
    except ImportError:
        pass
    try:
        if not cv2.ocl.haveOpenCL():
            return False, "none"
        cv2.ocl.setUseOpenCL(True)
        dev = cv2.ocl.Device.getDefault()
        return True, (dev.name() if dev else "") or "OpenCL"
    except Exception:
        return False, "none"


def _load_reference():
    current = Path(__file__).resolve()
    # ponytail: assets đã được chuyển vào pipeline/drawing/assets/ để tránh phụ thuộc submodule
    bundled = current.parent / "assets" / "scripts" / "stream_render.py"
    candidates = [
        bundled if bundled.is_file() else None,
        # Legacy: tìm trong references/ nếu dev vẫn còn submodule local
        Path(os.environ["VIDEO_CLONE_BUNDLE"]) / "references" / "whiteboard-stream-animation" / "scripts" / "stream_render.py"
        if os.environ.get("VIDEO_CLONE_BUNDLE") else None,
        current.parents[2] / "references" / "whiteboard-stream-animation" / "scripts" / "stream_render.py",
        current.parents[3] / "references" / "whiteboard-stream-animation" / "scripts" / "stream_render.py",
    ]
    source = next(
        (p for p in candidates if p is not None and p.is_file()),
        None,
    )
    if source is None:
        raise RuntimeError("whiteboard-stream-animation renderer is unavailable")
    spec = importlib.util.spec_from_file_location("videoclone_whiteboard_stream", source)
    if not spec or not spec.loader:
        raise RuntimeError("could not load whiteboard-stream-animation renderer")
    module = importlib.util.module_from_spec(spec)
    # dataclasses resolves postponed annotations through sys.modules while the
    # reference module is executing.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    # Bundled: pipeline/drawing/assets/images/ ; Legacy (references/): source.parent.parent/assets/
    bundled_hand = Path(__file__).parent / "assets" / "images" / "drawing-hand.png"
    hand = bundled_hand if bundled_hand.is_file() else source.parent.parent / "assets" / "drawing-hand.png"
    return module, hand


def _transcode_with_app_encoder(raw: Path, final: Path, fps: int, renderer_module):
    """Use the application's verified hardware encoder for the intermediate MP4.

    The reference project always invokes libx264 here.  Its actual drawing
    frames are still generated by OpenCV on CPU, but avoiding a second CPU
    H.264 pass makes the wait materially shorter on Apple/NVIDIA/Intel/AMD.
    """
    backend_root = Path(__file__).resolve().parents[2]
    if str(backend_root) not in sys.path:
        sys.path.insert(0, str(backend_root))
    try:
        from pipeline.core.media import h264_encoder_args

        command = [
            "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
            "-i", str(raw), "-an", "-r", str(fps),
            *h264_encoder_args(fast=True, throughput=True),
            "-movflags", "+faststart", str(final),
        ]
        result = subprocess.run(command, capture_output=True, text=True, timeout=900)
        if result.returncode == 0 and final.is_file():
            raw.unlink(missing_ok=True)
            print(f"ENCODER=app-hardware OUTPUT={final}")
            return final
        print(f"[warn] app hardware transcode failed: {(result.stderr or '').strip()[-300:]}")
    except Exception as exc:
        print(f"[warn] app hardware transcode unavailable: {exc}")
    # Keep the reference project's portable CPU/PyAV fallback for machines
    # whose FFmpeg has no usable hardware encoder.
    result = renderer_module.transcode_h264(raw, final)
    print(f"ENCODER=reference-fallback OUTPUT={result}")
    return result


def _finish_render(raw: Path, final: Path, fps: int, renderer_module, *, transcode: bool = True) -> Path:
    """Keep raw MP4V when the parent pipeline will perform the final H.264 encode."""
    return _transcode_with_app_encoder(raw, final, fps, renderer_module) if transcode else raw


def _ordered_grid_cells(renderer_module, renderer, order: str) -> list[tuple[int, int]]:
    """Build a visible pen route without changing the reference renderer.

    ``natural`` preserves its semantic object/text/contour grouping. The other
    choices only reorder the grid route; edge extraction and ink rendering stay
    untouched in the upstream implementation.
    """
    streams = list(renderer.ink_streams)
    if order == "natural":
        return renderer_module.flatten_streams(streams)
    if order == "region":
        # Complete one major visual region before moving to the next one.
        return renderer_module.flatten_streams(sorted(streams, key=len, reverse=True))

    cells = renderer_module.flatten_streams(streams)
    if not cells:
        return []
    if order == "reading":
        return sorted(cells, key=lambda cell: (cell[0], cell[1]))
    if order == "horizontal":
        rows: dict[int, list[tuple[int, int]]] = {}
        for cell in cells:
            rows.setdefault(cell[0], []).append(cell)
        return [
            cell for index, row in enumerate(sorted(rows))
            for cell in sorted(rows[row], key=lambda item: item[1], reverse=bool(index % 2))
        ]
    if order == "vertical":
        columns: dict[int, list[tuple[int, int]]] = {}
        for cell in cells:
            columns.setdefault(cell[1], []).append(cell)
        return [
            cell for index, column in enumerate(sorted(columns))
            for cell in sorted(columns[column], key=lambda item: item[0], reverse=bool(index % 2))
        ]
    if order == "center":
        centre_row = sum(row for row, _ in cells) / len(cells)
        centre_col = sum(column for _, column in cells) / len(cells)
        # Radius first reveals the centre; the angle makes the sweep circular
        # rather than the old top-to-bottom fill.
        return sorted(cells, key=lambda cell: (
            round(math.hypot(cell[0] - centre_row, cell[1] - centre_col), 1),
            math.atan2(cell[0] - centre_row, cell[1] - centre_col),
        ))
    return renderer_module.flatten_streams(streams)


def _apply_stroke_order(renderer_module, renderer, order: str) -> None:
    if order in {"natural", "outline"}:
        # Natural keeps semantic groups; outline keeps skeleton strokes and
        # their explicit pen lifts from the reference renderer.
        return
    if order == "region":
        renderer.ink_streams = sorted(renderer.ink_streams, key=len, reverse=True)
        renderer.stroke_path = renderer_module.flatten_streams(renderer.ink_streams)
        return
    route = _ordered_grid_cells(renderer_module, renderer, order)
    renderer.ink_streams = [route] if route else []
    renderer.stroke_path = route


# ── GPU / hot-path optimizations (ponytail: keep reference renderer unmodified) ──

def _apply_rendering_optimizations(renderer, renderer_module) -> bool:
    """Patch hot rendering methods for GPU-accelerated + optimized painting.

    Returns True when OpenCL (GPU) acceleration is active.
    """
    h, w = renderer.out_h, renderer.out_w
    cfg = renderer.cfg

    use_gpu, ocl_name = _opencl_device()
    if use_gpu:
        print(f"  GPU painting: OpenCL on {ocl_name}")
    else:
        print("  GPU painting: unavailable, using optimized CPU")

    # Pre-allocate reusable buffers (avoid per-call allocation + GC pressure)
    _segment_buf = np.zeros((h, w), dtype=np.uint8)
    _mask_buf    = np.zeros((h, w), dtype=np.uint8)
    # ink_pixels is bool HxW — convert once to uint8 for bitwise_and
    _ink_u8      = renderer.ink_pixels.astype(np.uint8)
    _snap_buf    = np.empty((h, w, 3), dtype=np.uint8)
    ink_thickness = max(1, cfg.ink_reveal_radius * 2 + 1)

    # Pre-convert color_img to float32 once (avoid per-stamp allocation)
    _color_f32 = renderer.color_img.astype(np.float32)

    def fast_reveal_ink_segment(start, end):
        """Bounding-box ROI: only process pixels near the stroke segment.

        For grid_edge=10 cells the bbox is typically ~30×30 px vs full 960×530 —
        ~1000× fewer elements per call, called ~17k times per render.
        """
        r = ink_thickness + 1
        x0 = max(0, min(start[0], end[0]) - r)
        x1 = min(w, max(start[0], end[0]) + r + 1)
        y0 = max(0, min(start[1], end[1]) - r)
        y1 = min(h, max(start[1], end[1]) + r + 1)
        if x1 <= x0 or y1 <= y0:
            return
        roi_h, roi_w = y1 - y0, x1 - x0
        seg_roi  = _segment_buf[y0:y1, x0:x1]
        mask_roi = _mask_buf[y0:y1, x0:x1]
        seg_roi[:] = 0
        cv2.line(seg_roi,
                 (start[0] - x0, start[1] - y0),
                 (end[0] - x0,   end[1] - y0),
                 255, thickness=ink_thickness, lineType=cv2.LINE_AA)
        np.bitwise_and(seg_roi, _ink_u8[y0:y1, x0:x1], out=mask_roi)
        mask3 = np.broadcast_to(mask_roi.view(bool)[:, :, np.newaxis], (roi_h, roi_w, 3))
        np.copyto(renderer.drawn[y0:y1, x0:x1], renderer.ink_paint[y0:y1, x0:x1], where=mask3)

    def fast_snapshot_with_tip(px, py):
        """GPU: convertScaleAbs on UMat. CPU: reuse pre-allocated uint8 buffer."""
        if use_gpu:
            umat = cv2.UMat(renderer.drawn)
            snap = cv2.convertScaleAbs(umat).get()
        else:
            np.copyto(_snap_buf, renderer.drawn, casting="unsafe")
            snap = _snap_buf
        if renderer.tip is not None:
            renderer.tip.stamp(snap, px, py)
        return snap

    def fast_color_stamp(px, py, disk):
        """Vectorized 3-channel blend: single broadcast op replaces Python loop."""
        radius = cfg.brush_radius
        y0, y1 = max(0, py - radius), min(h, py + radius + 1)
        x0, x1 = max(0, px - radius), min(w, px + radius + 1)
        if y1 <= y0 or x1 <= x0:
            return
        by0 = y0 - (py - radius)
        by1 = disk.shape[0] - ((py + radius + 1) - y1)
        bx0 = x0 - (px - radius)
        bx1 = disk.shape[1] - ((px + radius + 1) - x1)
        m3 = disk[by0:by1, bx0:bx1, np.newaxis]  # (H,W,1) broadcasts to 3ch
        target = renderer.drawn[y0:y1, x0:x1]
        source = _color_f32[y0:y1, x0:x1]
        # target = target*(1-m) + source*m  (in-place on the drawn canvas view)
        target *= (1.0 - m3)
        target += source * m3

    renderer._reveal_ink_segment = fast_reveal_ink_segment
    renderer._snapshot_with_tip = fast_snapshot_with_tip
    renderer._color_stamp = fast_color_stamp
    return use_gpu



def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("image")
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--total-ms", type=int, required=True)
    parser.add_argument("--fps", type=int, required=True)
    parser.add_argument("--grid-edge", type=int, required=True)
    parser.add_argument("--ink-path", choices=("grid", "skeleton"), required=True)
    parser.add_argument("--long-edge", type=int, required=True)
    parser.add_argument("--tool", choices=("pencil", "pen", "marker", "brush"), default="pencil")
    parser.add_argument("--thickness", type=int, default=2)
    parser.add_argument("--stroke-order", choices=("natural", "outline", "region", "reading", "center", "horizontal", "vertical"), default="natural")
    parser.add_argument("--bare-tip", action="store_true")
    parser.add_argument("--hand-png", default=None, help="Override hand sprite PNG path")
    parser.add_argument("--skip-transcode", action="store_true")
    args = parser.parse_args()

    renderer_module, hand_asset = _load_reference()
    # Custom sprite overrides default; --bare-tip suppresses all hand rendering
    if args.hand_png and Path(args.hand_png).is_file():
        hand_asset = Path(args.hand_png)
    source = Path(args.image)
    image = renderer_module._imread_any(source)
    if image is None:
        raise RuntimeError("could not decode drawing input image")
    total_seconds = max(.1, args.total_ms / 1000)
    thickness = max(1, min(8, args.thickness))
    # The reference renderer exposes separate ink and colour brushes. Mapping
    # the UI tools here makes each control change the rendered stroke, not only
    # the selected button state.
    tool_radius = {"pencil": 2, "pen": 3, "marker": 6, "brush": 8}[args.tool]
    color_fill = "brush" if args.tool == "brush" else "contour-wipe"
    config = renderer_module.Config(
        fps=args.fps,
        grid_edge=max(4, args.grid_edge),
        cap_long_edge=max(320, args.long_edge),
        ink_path_mode=args.ink_path,
        pause_mode="auto",
        color_fill=color_fill,
        ink_reveal_radius=max(tool_radius, thickness),
        brush_radius=max(16, thickness * 15),
        # Never let the final still frame eliminate ink/color animation.
        gaze_seconds=min(3.0, max(.35, total_seconds * .22)),
    )
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    raw = out_dir / f"drawing_{stamp}.mp4"
    final = out_dir / f"drawing_{stamp}_h264.mp4"
    renderer = renderer_module.StreamBoardRenderer(
        image, config, hand_asset if not args.bare_tip else None, args.bare_tip,
    )
    _apply_stroke_order(renderer_module, renderer, args.stroke_order)
    print(f"STROKE_ORDER={args.stroke_order}")

    # Apply per-frame painting optimizations (OpenCL snapshot, buffer reuse,
    # vectorized blend). H.264 encoding uses shared GPU detection via jobs.py.
    gpu_active = _apply_rendering_optimizations(renderer, renderer_module)

    renderer.render_to(raw, args.total_ms)
    result = _finish_render(raw, final, args.fps, renderer_module, transcode=not args.skip_transcode)
    print(f"GPU_PAINTING={'1' if gpu_active else '0'}")
    print(f"OUTPUT={result}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
