"""Adapter for the MIT whiteboard streaming renderer used by Drawing jobs.

It keeps the reference renderer intact while applying Video Clone's selected
duration, FPS and output resolution.  In particular, short previews reserve a
small gaze segment instead of consuming the entire clip before any ink lands.
"""
from __future__ import annotations

import argparse
import datetime
import importlib.util
import math
import os
import subprocess
import sys
from pathlib import Path


def _load_reference():
    current = Path(__file__).resolve()
    candidates = [
        Path(os.environ["VIDEO_CLONE_BUNDLE"]) if os.environ.get("VIDEO_CLONE_BUNDLE") else None,
        current.parents[2],  # packaged Resources/_internal root
        current.parents[3],  # repository root in development
    ]
    source = next(
        (
            root / "references" / "whiteboard-stream-animation" / "scripts" / "stream_render.py"
            for root in candidates
            if root is not None
            and (root / "references" / "whiteboard-stream-animation" / "scripts" / "stream_render.py").is_file()
        ),
        None,
    )
    if source is None:
        raise RuntimeError("whiteboard-stream-animation renderer is unavailable")
    spec = importlib.util.spec_from_file_location("videoclone_whiteboard_stream", source)
    if not spec or not spec.loader:
        raise RuntimeError("could not load whiteboard-stream-animation renderer")
    module = importlib.util.module_from_spec(spec)
    # dataclasses resolves postponed annotations through sys.modules while the
    # reference module is executing.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module, source.parent.parent / "assets" / "drawing-hand.png"


def _transcode_with_app_encoder(raw: Path, final: Path, fps: int, renderer_module):
    """Use the application's verified hardware encoder for the intermediate MP4.

    The reference project always invokes libx264 here.  Its actual drawing
    frames are still generated by OpenCV on CPU, but avoiding a second CPU
    H.264 pass makes the wait materially shorter on Apple/NVIDIA/Intel/AMD.
    """
    backend_root = Path(__file__).resolve().parents[2]
    if str(backend_root) not in sys.path:
        sys.path.insert(0, str(backend_root))
    try:
        from pipeline.core.media import h264_encoder_args

        command = [
            "ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
            "-i", str(raw), "-an", "-r", str(fps),
            *h264_encoder_args(fast=True, throughput=True),
            "-movflags", "+faststart", str(final),
        ]
        result = subprocess.run(command, capture_output=True, text=True, timeout=900)
        if result.returncode == 0 and final.is_file():
            raw.unlink(missing_ok=True)
            print(f"ENCODER=app-hardware OUTPUT={final}")
            return final
        print(f"[warn] app hardware transcode failed: {(result.stderr or '').strip()[-300:]}")
    except Exception as exc:
        print(f"[warn] app hardware transcode unavailable: {exc}")
    # Keep the reference project's portable CPU/PyAV fallback for machines
    # whose FFmpeg has no usable hardware encoder.
    result = renderer_module.transcode_h264(raw, final)
    print(f"ENCODER=reference-fallback OUTPUT={result}")
    return result


def _ordered_grid_cells(renderer_module, renderer, order: str) -> list[tuple[int, int]]:
    """Build a visible pen route without changing the reference renderer.

    ``natural`` preserves its semantic object/text/contour grouping. The other
    choices only reorder the grid route; edge extraction and ink rendering stay
    untouched in the upstream implementation.
    """
    streams = list(renderer.ink_streams)
    if order == "natural":
        return renderer_module.flatten_streams(streams)
    if order == "region":
        # Complete one major visual region before moving to the next one.
        return renderer_module.flatten_streams(sorted(streams, key=len, reverse=True))

    cells = renderer_module.flatten_streams(streams)
    if not cells:
        return []
    if order == "reading":
        return sorted(cells, key=lambda cell: (cell[0], cell[1]))
    if order == "horizontal":
        rows: dict[int, list[tuple[int, int]]] = {}
        for cell in cells:
            rows.setdefault(cell[0], []).append(cell)
        return [
            cell for index, row in enumerate(sorted(rows))
            for cell in sorted(rows[row], key=lambda item: item[1], reverse=bool(index % 2))
        ]
    if order == "vertical":
        columns: dict[int, list[tuple[int, int]]] = {}
        for cell in cells:
            columns.setdefault(cell[1], []).append(cell)
        return [
            cell for index, column in enumerate(sorted(columns))
            for cell in sorted(columns[column], key=lambda item: item[0], reverse=bool(index % 2))
        ]
    if order == "center":
        centre_row = sum(row for row, _ in cells) / len(cells)
        centre_col = sum(column for _, column in cells) / len(cells)
        # Radius first reveals the centre; the angle makes the sweep circular
        # rather than the old top-to-bottom fill.
        return sorted(cells, key=lambda cell: (
            round(math.hypot(cell[0] - centre_row, cell[1] - centre_col), 1),
            math.atan2(cell[0] - centre_row, cell[1] - centre_col),
        ))
    return renderer_module.flatten_streams(streams)


def _apply_stroke_order(renderer_module, renderer, order: str) -> None:
    if order in {"natural", "outline"}:
        # Natural keeps semantic groups; outline keeps skeleton strokes and
        # their explicit pen lifts from the reference renderer.
        return
    if order == "region":
        renderer.ink_streams = sorted(renderer.ink_streams, key=len, reverse=True)
        renderer.stroke_path = renderer_module.flatten_streams(renderer.ink_streams)
        return
    route = _ordered_grid_cells(renderer_module, renderer, order)
    renderer.ink_streams = [route] if route else []
    renderer.stroke_path = route


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("image")
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--total-ms", type=int, required=True)
    parser.add_argument("--fps", type=int, required=True)
    parser.add_argument("--grid-edge", type=int, required=True)
    parser.add_argument("--ink-path", choices=("grid", "skeleton"), required=True)
    parser.add_argument("--long-edge", type=int, required=True)
    parser.add_argument("--tool", choices=("pencil", "pen", "marker", "brush"), default="pencil")
    parser.add_argument("--thickness", type=int, default=2)
    parser.add_argument("--stroke-order", choices=("natural", "outline", "region", "reading", "center", "horizontal", "vertical"), default="natural")
    parser.add_argument("--bare-tip", action="store_true")
    args = parser.parse_args()

    renderer_module, hand_asset = _load_reference()
    source = Path(args.image)
    image = renderer_module._imread_any(source)
    if image is None:
        raise RuntimeError("could not decode drawing input image")
    total_seconds = max(.1, args.total_ms / 1000)
    thickness = max(1, min(8, args.thickness))
    # The reference renderer exposes separate ink and colour brushes. Mapping
    # the UI tools here makes each control change the rendered stroke, not only
    # the selected button state.
    tool_radius = {"pencil": 2, "pen": 3, "marker": 6, "brush": 8}[args.tool]
    color_fill = "brush" if args.tool == "brush" else "contour-wipe"
    config = renderer_module.Config(
        fps=args.fps,
        grid_edge=max(4, args.grid_edge),
        cap_long_edge=max(320, args.long_edge),
        ink_path_mode=args.ink_path,
        pause_mode="auto",
        color_fill=color_fill,
        ink_reveal_radius=max(tool_radius, thickness),
        brush_radius=max(16, thickness * 15),
        # Never let the final still frame eliminate ink/color animation.
        gaze_seconds=min(3.0, max(.35, total_seconds * .22)),
    )
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    raw = out_dir / f"drawing_{stamp}.mp4"
    final = out_dir / f"drawing_{stamp}_h264.mp4"
    renderer = renderer_module.StreamBoardRenderer(
        image, config, hand_asset if not args.bare_tip else None, args.bare_tip,
    )
    _apply_stroke_order(renderer_module, renderer, args.stroke_order)
    print(f"STROKE_ORDER={args.stroke_order}")
    renderer.render_to(raw, args.total_ms)
    result = _transcode_with_app_encoder(raw, final, args.fps, renderer_module)
    print(f"OUTPUT={result}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
